### ISSUE TITLE
400 Bad Request on delete

### ISSUE THREAD

**Issue by jaydgus** [azure-contrib/node-azure-search#38]
I'm trying to use the api to delete a document via POST from Postman and I get this error :
{
    "error": {
        "code": "",
        "message": "The request is invalid. Details: parameters : The parameter 'CompositeKey' in the request payload is not a valid parameter for the operation 'index'.\r\n"
    }
}

This is the url and post body in a format recommended by the documentation and I'm using our Admin API Key in the header too:
https://[svcname].search.windows.net/indexes/[indexname]/docs/index?api-version=2019-05-06

{  
	"@search.action": "delete",  
	"CompositeKey": "#nicelongalphanumericvaluethatsuniquetothisdoc#"
}

Thanks,
Jay

**Comment by richorama** [comment]
Hi @jaydgus,

Is your issue related to this javascript library, or the actual service itself? It sounds that if you're using postman, then you're bypassing this library? In which case you'd need to raise the issue with Microsoft.

If this issue is with this library, would you mind including a code snipped which reproduces the problem? Of course I would recommend removing any API keys or other identifiable strings.

Thanks.

Richard.

**Comment by jaydgus** [comment]
Sorry, I looks like I need to go Azure support. Thanks!

**Comment by morrisond91** [comment]
@jaydgus - did you ever get your issue over here fixed: https://github.com/IdentityServer/IdentityServer4/issues/658#issuecomment-384010928

sorry i know its not related here but i have no other way of contacting you :)
